import { Product } from "./types/Product";

export const sampleProducts: Product[] = [
  {
    name: "Nike Slim Shirt",
    slug: "nike-slim-shirt",
    category: "Shoes",
    image: "../images/N9.jpeg",
    price: 120,
    countInStock: 10,
    brand: "Nike",
    rating: 2.5,
    numReviews: 9,
    description: "high quality shirt",
  },
  {
    name: "Nike Black Sweat jacket",
    slug: "Nike Black Sweat jacket",
    category: "Jackets",
    image: "../images/N2.jpeg",
    price: 100,
    countInStock: 20,
    brand: "Nike",
    rating: 4.0,
    numReviews: 23,
    description: "high quality product",
  },
  {
    name: "Nike Gray Sports Pants",
    slug: "Nike Gray Sports Pants",
    category: "Pants",
    image: "../images/N12.jpeg",
    price: 220,
    countInStock: 20,
    brand: "Nike",
    rating: 4.8,
    numReviews: 17,
    description: "high quality product",
  },
  {
    name: "Adidas White Sports Shirt",
    slug: "Adidas White Sports Shirt",
    category: "Shirt",
    image: "../images/A4.jpeg",
    price: 78,
    countInStock: 15,
    brand: "Adidas",
    rating: 4.5,
    numReviews: 18,
    description: "high quality product",
  },
];
